# Site settings
title: Auto Trader Engineering Blog
description: > # this means to ignore newlines until "baseurl:"
  A look at the interesting parts of the engineering behind Auto Trader.

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

paginate: 20
paginate_path: "/page-:num/"
google_analytics_tracking_id: UA-20049363-3
github:
  username: autotraderuk
twitter:
  username: autotraderlife
facebook:
  username: autotraderlife

include_repo_ribbon: false
include_comments: false

logo: /images/at-chevron_4096x4096.png

defaults:
  - scope:
      path: ""
    values:
      image: /images/at-chevron_4096x4096.png