# Site settings
title: Auto Trader Engineering Blog
description: > # this means to ignore newlines until "baseurl:"
  A look at the interesting parts of the engineering behind Auto Trader.

# Build settings
markdown: kramdown
kramdown:
  input: GFM

gems: [jekyll-paginate]

paginate: 20
paginate_path: "/page-:num/"
google_analytics_tracking_id: "UA-20049363-3"
github_username: "autotraderuk"
twitter_username: "autotraderlife"
facebook_username: "autotraderlife"

include_repo_ribbon: false